### ISSUE TITLE
[Bug] No sound file found (might be my installation)

### ISSUE THREAD

**Issue by Kingproone** [dhruv8sh/arch-update-checker#39]
My plasma install has been upgraded from 5.27 and something might have been left out, plus it only happens once per boot, when I first check for updates, any idea why this might be?
![Screenshot_20240420_140839](https://github.com/dhruv8sh/arch-update-checker/assets/118820223/285be986-7121-4ed9-a734-4568742b9472)

**Comment by tdtooke** [comment]
The same thing happened to me.  I believe your problem is most likely you don't have a knotifications6 directory in ~/.local/share.  What I did was create that directory then reinstall the applet.  All my other notifications are in /usr/share but you'd need root access to do that and we usually don't install plasmoids that way.

**Comment by Kingproone** [comment]
So is this a arch problem, that it didnt update correctly and something was missed out, or the applet, for looking in there?

**Comment by dhruv8sh** [comment]
No this was caused due to an unintentional new-line character. It's fixed now!
